### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by stevk** [bghgary/glTF-Asset-Generator#63]
These are the attributes that should have tests created next. They are listed in order of priority.

- [ ] Scene (ETA Sept 12)
Zero scenes
One Scene
Multiple Scenes 
One Scene w/ multiple nodes
Multiple Scenes w/ multiple nodes
Multiple Scenes w/ the same node

- [ ] Node (ETA Sept 18)
Node w/ child
Node w/ children
Node w/ deep node hierarchy
Node with transformations (Combo?)
Node w/ mesh?
Camera
skin
matrix (transformation)
rotation
scale
translation
weights

- [ ] Mesh (ETA Sept 20)
Single primitive?
multiple primitives
weights (morph targets)

- [ ] Primitives
indices?
mode
targets

- [ ] Primitives_Attributes
position
normal
tangent
TexCoord_0
TexCoord_1
Color_0
Joints_0
Weights_0

- [ ] Accessors
?

- [ ] Buffer
?

- [ ] BufferView
?

**Comment by bghgary** [comment]
I think Mesh, Primitives, Primitive_Attributes should be first in this list. Scene, node, etc. can go later.

**Comment by stevk** [comment]
Made that update.

**Comment by andreasplesch** [comment]
Since there is a question mark for buffers, perhaps add individual buffers for POSITION, INDEX, NORMAL, animation channels etc. Some engines may expect that there is only one buffer, or one for geometry and one for animation.

**Comment by bghgary** [comment]
Sure, we can do that. Do you mind filing a separate issue so that it doesn't get lost?

**Comment by andreasplesch** [comment]
Please see #440.

**Comment by bghgary** [comment]
Thanks @andreasplesch!

**Comment by XuWenzheng** [comment]
@bghgary Could you please add YuuuZhang to Collaborators so that she can edit on the feature roadmap in the future? YuuuZhang is the owner of Babylon.js in OMG QA offshore team.
